### ISSUE TITLE
Allow clicking to proceed through cut scenes quickly

### ISSUE THREAD

**Issue by Matt5sean3** [Matt5sean3/moon-defender#16]

**Comment by aaron-HackRVA** [comment]
The cut scenes should be activated by a click only. To go through quickly, but also to give reader enough time to read longer scenes. (take the timer off).

**Comment by Matt5sean3** [comment]
I've removed the timer for the cut scene so now they have to be manually clicked through. See PR #26. You may want to add a message to the art that says "click to continue" or something like that so people aren't just sitting at the screen wondering what to do.
