### ISSUE TITLE
Add a victory screen

### ISSUE THREAD

**Issue by Matt5sean3** [Matt5sean3/moon-defender#25]
There needs to be something at the end to signify success. Maybe show a cut image then roll credits.

**Comment by aaron-HackRVA** [comment]
We did create a victory screen as well as a game over screen - but I didn't put in credits. I can probably just do credits in the same screen if you don't want to mess with "rolling" them. I'll add the image to slack for grabbing.

Eli - Code & Art
Matt - Code
Dustin - Code & Art
Aaron - Art

**Comment by Matt5sean3** [comment]
Yeah, there's no point in rolling, just have a credits screen. The gameover screen works and is implemented. After victory in story mode the game just freezes. Is the victory screen graphic in the repository?

**Comment by Matt5sean3** [comment]
Finger slipped on the close issue button

**Comment by Matt5sean3** [comment]
I added a credits screen that sticks more to web video game conventions

**Comment by Matt5sean3** [comment]
The victory screen has been completed
